variable "import_id" {
  description = "Base64 URL identifier generated by the seed workflow."
  type        = string
}

module "record" {
  source = "../modules/record"
}

# TODO: Preserve the imported object's identity while moving it into the module.

output "record_id" {
  value = module.record.id
}
