variable "import_id" {
  description = "Base64 URL identifier generated by the seed workflow."
  type        = string
}

module "record" {
  source = "../modules/record"
}

moved {
  from = random_id.legacy_record
  to   = module.record.random_id.this
}
output "record_id" {
  value = module.record.id
}
