variable "import_id" {
  description = "Base64 URL identifier generated by the seed workflow."
  type        = string
}

resource "random_id" "legacy_record" {
  byte_length = 8
}

import {
  to = random_id.legacy_record
  id = var.import_id
}

output "record_id" {
  value = random_id.legacy_record.b64_url
}
