variable "import_id" {
  description = "Base64 URL identifier generated by the seed workflow."
  type        = string
}

resource "random_id" "legacy_record" {
  byte_length = 8
}

# TODO: Adopt the seeded identity at the existing root resource address.

output "record_id" {
  value = random_id.legacy_record.b64_url
}
